### ISSUE TITLE
Incompatible with stable Plaso release (1.4 atm)

### ISSUE THREAD

**Issue by rodgermoore** [libyal/winevt-kb#10]
If a user wants to build its own winevt-kb.db it needs these scripts. At this moment these scripts depend on dfvfs-20160227 or higher. Plaso Stable version 1.4 comes with dfvfs-20160108. In the future, is it possible to make stable releases of packages/scripts like these linked to stable releases of Plaso? Tnx

**Comment by joachimmetz** [comment]
Good to hear someone is using this functionality. What if I add a tool to plaso that offers the same functionality? Would that work for you?

I have different plans for this project long term.

**Comment by rodgermoore** [comment]
That would be even better.

**Comment by joachimmetz** [comment]
Ack, tracking progress in https://github.com/log2timeline/plaso/issues/636, closing this issue.
