### ISSUE TITLE
missing comma in setup.py

### ISSUE THREAD

**Issue by hiddenillusion** [libyal/winevt-kb#12]
```
user: ~/winevt-kb $ sudo python setup.py install
  File "setup.py", line 139
    cmdclass={
           ^
```

`setup.py` is missing a comma after the [`scripts`](https://github.com/libyal/winevt-kb/blob/master/setup.py#L138) list

**Comment by joachimmetz** [comment]
thx I'll have a look at this as soon as I get back to this: https://github.com/log2timeline/plaso/issues/636

**Comment by joachimmetz** [comment]
https://github.com/libyal/winevt-kb/commit/0ce32d94fc42348d70e90abb64329e081f6a7046
