### ISSUE TITLE
AttributeError: 'module' object has no attribute 'MESSAGE_FILE_TYPE_EVENT'

### ISSUE THREAD

**Issue by SkiTheSlicer** [libyal/winevt-kb#13]
After installing dependencies, cloning and installing master, running `export.py --db winevt-rc_new.db --string_format pep3101 dir_from_extract/` results in:
`AttributeError: 'module' object has no attribute 'MESSAGE_FILE_TYPE_EVENT'`

Fixed with:
```
unzip /usr/local/lib/python2.7/dist-packages/winevtrc-20160418-py2.7.egg EGG-INFO/scripts/export.py
sed -i 's|database.MESSAGE_FILE_TYPE_EVENT|database.definitions.MESSAGE_FILE_TYPE_EVENT|' EGG-INFO/scripts/export.py
sudo zip -u /usr/local/lib/python2.7/dist-packages/winevtrc-20160418-py2.7.egg EGG-INFO/scripts/export.py
```

**Comment by joachimmetz** [comment]
Thx for the report. I'll have a look if I reproduce this when time permits. Currently I'm working on improving test  coverage, for better plaso integration eventually.

**Comment by joachimmetz** [comment]
Looks like the issue has been addressed in the meantime
